"""empty message

Revision ID: 0b3139de028c
Revises: 35736c15e92d
Create Date: 2020-03-27 10:34:55.813534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b3139de028c'
down_revision = '35736c15e92d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('image', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'image')
    # ### end Alembic commands ###
