"""empty message

Revision ID: 13a9af77f475
Revises: 67fdaca2c95a
Create Date: 2020-04-14 03:37:17.217391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13a9af77f475'
down_revision = '67fdaca2c95a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('pic', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
