"""empty message

Revision ID: 1ac4cb5dc1c3
Revises: 864b7d2f0b0e
Create Date: 2020-03-26 13:51:09.280224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac4cb5dc1c3'
down_revision = '864b7d2f0b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('email', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'email')
    # ### end Alembic commands ###
