"""empty message

Revision ID: 2bf03a0daad4
Revises: 65908de93686
Create Date: 2020-04-16 04:08:18.818613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf03a0daad4'
down_revision = '65908de93686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('biography', sa.String(length=600), nullable=True))
    op.drop_column('user_profiles', 'bibliography')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('bibliography', sa.VARCHAR(length=600), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'biography')
    # ### end Alembic commands ###
