"""empty message

Revision ID: 388045053837
Revises: 2bf03a0daad4
Create Date: 2020-04-16 04:12:18.832524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388045053837'
down_revision = '2bf03a0daad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('biography', sa.String(length=600), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('fileName', sa.String(length=100), nullable=True),
    sa.Column('date_joined', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
