"""empty message

Revision ID: 65908de93686
Revises: a64fca1ca97a
Create Date: 2020-04-15 17:44:21.639389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65908de93686'
down_revision = 'a64fca1ca97a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('bibliography', sa.String(length=600), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('fileName', sa.String(length=100), nullable=True),
    sa.Column('date_joined', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
