"""empty message

Revision ID: 6dfbff8d8ec6
Revises: 13a9af77f475
Create Date: 2020-04-14 13:55:44.629940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfbff8d8ec6'
down_revision = '13a9af77f475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('fileName', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('pic', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'pic')
    op.drop_column('user_profiles', 'fileName')
    # ### end Alembic commands ###
