"""empty message

Revision ID: 83096f4477d1
Revises: 6dfbff8d8ec6
Create Date: 2020-04-14 18:02:09.501052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83096f4477d1'
down_revision = '6dfbff8d8ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('bibliography', sa.String(length=200), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('fileName', sa.String(length=100), nullable=True),
    sa.Column('pic', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
