"""empty message

Revision ID: a64fca1ca97a
Revises: 83096f4477d1
Create Date: 2020-04-15 17:43:27.925613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a64fca1ca97a'
down_revision = '83096f4477d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('date_joined', sa.String(length=40), nullable=True))
    op.drop_column('user_profiles', 'pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('pic', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'date_joined')
    # ### end Alembic commands ###
